create table public."USUARIO" (
  id_usuario bigint generated by default as identity not null,
  date_register date null,
  first_name character varying not null,
  second_name character varying null,
  first_last_name character varying null,
  second_last_name character varying null,
  rut numeric null,
  fono numeric null,
  mail character varying null,
  nacionalidad character varying null,
  rol_nbr numeric null,
  rol_desc character varying null,
  date_birth date null,
  gender_nbr numeric null,
  gender_desc character varying null,
  rut_dv numeric null,
  pass character varying null,
  constraint USUARIO_pkey primary key (id_usuario)
) TABLESPACE pg_default;

-- PERMISOS

-- SELECT
create policy "allow select"
on "USUARIO"
for select
to anon
using (true);

-- INSERT
create policy "allow insert"
on "USUARIO"
for insert
to anon
with check (true);

-- UPDATE
create policy "allow update"
on "USUARIO"
for update
to anon
using (true);

-- DELETE
create policy "allow delete"
on "USUARIO"
for delete
to anon
using (true);